import React, { useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { AlertCircle, ArrowLeft, ExternalLink, ShieldCheck, MessageCircle } from "lucide-react";
import { adaptBackendRecommendation } from "../../services/api";
import { Badge } from "../../components/common/Badge";
import { Button } from "../../components/common/Button";
import { Card, CardContent, CardHeader, CardTitle } from "../../components/common/Card";

function ErrorPanel({ message, onRetry }) {
  return <Card className="max-w-2xl mx-auto overflow-hidden border-slate-200 bg-white shadow-sm"><CardContent className="relative p-10 text-center sm:p-14"><div className="pointer-events-none absolute -left-10 -top-10 h-32 w-32 rounded-full bg-violet-100/70" /><div className="pointer-events-none absolute -bottom-14 -right-8 h-36 w-36 rounded-full bg-orange-100/70" /><div className="relative mx-auto grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-violet-100 to-fuchsia-100 text-violet-600"><MessageCircle className="h-8 w-8" /></div><div className="relative mt-5"><h2 className="text-xl font-bold text-slate-900">Nothing to recommend yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-600">{message}</p></div><div className="relative mt-7"><Button variant="primary" onClick={onRetry}>Start a recommendation</Button></div></CardContent></Card>;
}

export const Results = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const [activeEvidence, setActiveEvidence] = useState(null);
  const stored = (() => { try { return JSON.parse(sessionStorage.getItem("normwise:lastRecommendation") || "null"); } catch { return null; } })();
  const response = location.state?.apiResponse || stored?.apiResponse;
  const result = useMemo(() => adaptBackendRecommendation(response), [response]);

  if (!response || !result) return <ErrorPanel message="Submit a requirement to see a verified Indian Standard recommendation here." onRetry={() => navigate("/recommend")} />;
  if (result.confidenceState === "no_confident_match" || !result.recommendedStandard) return <Card className="max-w-2xl mx-auto border-amber-200 bg-amber-50/50"><CardContent className="p-8 text-center space-y-4"><AlertCircle className="w-10 h-10 mx-auto text-amber-600" /><h2 className="text-lg font-bold text-slate-900">No confident match found</h2><p className="text-sm text-slate-700">The backend could not identify a sufficiently confident standard for this requirement.</p><Button variant="primary" onClick={() => navigate("/recommend")}>Refine requirement</Button></CardContent></Card>;

  const isReviewRequired = result.confidenceState === "review_required";
  return <div className="max-w-7xl mx-auto space-y-6 animate-in fade-in duration-200">
    <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3 border-b border-slate-200 pb-4"><div><button onClick={() => navigate("/recommend")} className="text-xs text-blue-700 font-semibold inline-flex items-center gap-1 mb-2"><ArrowLeft className="w-3.5 h-3.5" /> New recommendation</button><h1 className="text-2xl font-bold tracking-tight text-slate-900">Recommendation result</h1><p className="text-sm text-slate-600 mt-1">{result.requirement}</p></div><Badge variant={isReviewRequired ? "review" : "current"} dot>{isReviewRequired ? "Review required" : "High confidence"}</Badge></div>
    {isReviewRequired && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 flex gap-3"><AlertCircle className="w-5 h-5 shrink-0" /><span>This result requires human verification before procurement use.</span></div>}
    <Card className="border-blue-200 shadow-sm"><CardHeader className="pb-3 border-b border-slate-100"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2"><div><p className="text-xs uppercase tracking-wider font-bold text-blue-700">Primary standard</p><CardTitle className="text-xl mt-1">{result.recommendedStandard}</CardTitle></div><div className="text-left sm:text-right"><p className="text-xs text-slate-500">Confidence</p><p className="text-2xl font-bold text-emerald-700">{result.confidence}%</p></div></div></CardHeader><CardContent className="p-5 space-y-4"><h2 className="text-base font-semibold text-slate-900">{result.standardTitle}</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-sm"><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><span className="block text-xs text-slate-500">Status</span><strong>{result.currentnessStatus}</strong></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><span className="block text-xs text-slate-500">Ranking method</span><strong>{result.rankingMethod || "Not available"}</strong></div><div className="rounded-lg bg-slate-50 border border-slate-200 p-3"><span className="block text-xs text-slate-500">Certification</span><strong>{result.certification || "Not available"}</strong></div></div><div className="flex items-center gap-2 text-xs text-slate-600"><ShieldCheck className="w-4 h-4 text-blue-700" /> Data returned by the verified backend recommendation service.</div></CardContent></Card>
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle className="text-base">Related standards</CardTitle></CardHeader><CardContent>{result.alliedStandards.length ? <div className="space-y-3">{result.alliedStandards.map((item) => <div key={item.id || item.standardNumber} className="border-b border-slate-100 pb-3 last:border-0"><div className="font-semibold text-slate-900">{item.standardNumber || "Not available"}</div><div className="text-sm text-slate-600">{item.title || "Title not available"}</div><div className="text-xs text-slate-500 mt-1">{item.relationshipType || "Relationship not specified"}</div></div>)}</div> : <p className="text-sm text-slate-500">No related standards were returned.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Evidence and sources</CardTitle></CardHeader><CardContent>{result.evidence.length ? <div className="space-y-3">{result.evidence.map((item, index) => <button type="button" key={item.id || index} onClick={() => setActiveEvidence(item)} className="w-full text-left border-b border-slate-100 pb-3 last:border-0 hover:bg-slate-50 rounded p-1"><div className="font-semibold text-slate-900">{item.category}</div><div className="text-sm text-slate-600">{item.excerpt || "Evidence text not available."}</div><div className="text-xs text-blue-700 mt-1">{item.clause || item.clauseTitle || "Source reference available"}{item.sourceUrl ? <ExternalLink className="inline w-3 h-3 ml-1" /> : null}</div></button>)}</div> : <p className="text-sm text-slate-500">No evidence records were returned.</p>}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">Alternative candidates</CardTitle></CardHeader><CardContent>{result.alternatives.length ? <div className="grid grid-cols-1 md:grid-cols-2 gap-3">{result.alternatives.map((item) => <div key={item.id || item.standardNumber} className="rounded-lg border border-slate-200 p-3"><div className="font-semibold">{item.standardNumber}</div><div className="text-sm text-slate-600">{item.title}</div><div className="text-xs text-slate-500 mt-1">Candidate score: {item.matchScore}</div></div>)}</div> : <p className="text-sm text-slate-500">No alternative candidates were returned.</p>}</CardContent></Card>
    {activeEvidence && <div role="dialog" className="fixed inset-0 z-40 bg-slate-900/30 flex items-center justify-center p-4" onClick={() => setActiveEvidence(null)}><Card className="max-w-lg w-full" onClick={(event) => event.stopPropagation()}><CardHeader><CardTitle className="text-base">Evidence detail</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{activeEvidence.excerpt || "Evidence text not available."}</p><p className="text-xs text-slate-500">{activeEvidence.clause || activeEvidence.clauseTitle || "Source reference not available."}</p><Button variant="outline" onClick={() => setActiveEvidence(null)}>Close</Button></CardContent></Card></div>}
  </div>;
};
