/**
 * Frontend Constants for NormWise
 */
export const RecommendationStatus = {
  PENDING_REVIEW: "PENDING_REVIEW",
  ACCEPTED: "ACCEPTED",
  UNDER_TECHNICAL_REVIEW: "UNDER_TECHNICAL_REVIEW",
  CLARIFICATION_REQUESTED: "CLARIFICATION_REQUESTED",
  NOT_APPLICABLE: "NOT_APPLICABLE",
};

export const StandardStatus = {
  CURRENT: "CURRENT",
  SUPERSEDED: "SUPERSEDED",
  WITHDRAWN: "WITHDRAWN",
  UNDER_REVIEW: "UNDER_REVIEW",
  UNKNOWN: "UNKNOWN",
};

export const UserRole = {
  PROCUREMENT_OFFICER: "PROCUREMENT_OFFICER",
  TECHNICAL_REVIEWER: "TECHNICAL_REVIEWER",
  ADMIN: "ADMIN",
  AUDITOR: "AUDITOR",
};

export const EvidenceType = {
  SCOPE: "SCOPE",
  REQUIREMENT: "REQUIREMENT",
  MATERIAL: "MATERIAL",
  CERTIFICATION: "CERTIFICATION",
  CURRENTNESS: "CURRENTNESS",
  RELATED_STANDARD: "RELATED_STANDARD",
  TEST_METHOD: "TEST_METHOD",
};

export const API_BASE_URL = import.meta.env.VITE_API_URL || "/api";
